package engine

// VoiceProfile holds metadata for a Kokoro speaker voice.
type VoiceProfile struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Gender      string `json:"gender"`
	Description string `json:"description"`
	Language    string `json:"language,omitempty"`
}

// AvailableKokoroV11Voices contains the full 103 speaker profiles for kokoro-multi-lang-v1_1.
var AvailableKokoroV11Voices = []VoiceProfile{
	{ID: "af_maple", Name: "Maple (American Female, Default)", Gender: "female", Description: "Warm, natural American English female"},
	{ID: "af_sol", Name: "Sol (American Female)", Gender: "female", Description: "Clear conversational American female"},
	{ID: "bf_vale", Name: "Vale (British Female)", Gender: "female", Description: "Expressive British English female"},
	{ID: "zf_001", Name: "zf_001 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_001"},
	{ID: "zf_002", Name: "zf_002 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_002"},
	{ID: "zf_003", Name: "zf_003 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_003"},
	{ID: "zf_004", Name: "zf_004 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_004"},
	{ID: "zf_005", Name: "zf_005 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_005"},
	{ID: "zf_006", Name: "zf_006 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_006"},
	{ID: "zf_007", Name: "zf_007 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_007"},
	{ID: "zf_008", Name: "zf_008 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_008"},
	{ID: "zf_017", Name: "zf_017 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_017"},
	{ID: "zf_018", Name: "zf_018 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_018"},
	{ID: "zf_019", Name: "zf_019 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_019"},
	{ID: "zf_021", Name: "zf_021 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_021"},
	{ID: "zf_022", Name: "zf_022 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_022"},
	{ID: "zf_023", Name: "zf_023 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_023"},
	{ID: "zf_024", Name: "zf_024 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_024"},
	{ID: "zf_026", Name: "zf_026 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_026"},
	{ID: "zf_027", Name: "zf_027 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_027"},
	{ID: "zf_028", Name: "zf_028 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_028"},
	{ID: "zf_032", Name: "zf_032 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_032"},
	{ID: "zf_036", Name: "zf_036 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_036"},
	{ID: "zf_038", Name: "zf_038 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_038"},
	{ID: "zf_039", Name: "zf_039 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_039"},
	{ID: "zf_040", Name: "zf_040 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_040"},
	{ID: "zf_042", Name: "zf_042 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_042"},
	{ID: "zf_043", Name: "zf_043 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_043"},
	{ID: "zf_044", Name: "zf_044 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_044"},
	{ID: "zf_046", Name: "zf_046 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_046"},
	{ID: "zf_047", Name: "zf_047 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_047"},
	{ID: "zf_048", Name: "zf_048 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_048"},
	{ID: "zf_049", Name: "zf_049 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_049"},
	{ID: "zf_051", Name: "zf_051 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_051"},
	{ID: "zf_059", Name: "zf_059 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_059"},
	{ID: "zf_060", Name: "zf_060 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_060"},
	{ID: "zf_067", Name: "zf_067 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_067"},
	{ID: "zf_070", Name: "zf_070 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_070"},
	{ID: "zf_071", Name: "zf_071 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_071"},
	{ID: "zf_072", Name: "zf_072 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_072"},
	{ID: "zf_073", Name: "zf_073 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_073"},
	{ID: "zf_074", Name: "zf_074 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_074"},
	{ID: "zf_075", Name: "zf_075 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_075"},
	{ID: "zf_076", Name: "zf_076 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_076"},
	{ID: "zf_077", Name: "zf_077 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_077"},
	{ID: "zf_078", Name: "zf_078 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_078"},
	{ID: "zf_079", Name: "zf_079 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_079"},
	{ID: "zf_083", Name: "zf_083 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_083"},
	{ID: "zf_084", Name: "zf_084 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_084"},
	{ID: "zf_085", Name: "zf_085 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_085"},
	{ID: "zf_086", Name: "zf_086 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_086"},
	{ID: "zf_087", Name: "zf_087 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_087"},
	{ID: "zf_088", Name: "zf_088 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_088"},
	{ID: "zf_090", Name: "zf_090 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_090"},
	{ID: "zf_092", Name: "zf_092 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_092"},
	{ID: "zf_093", Name: "zf_093 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_093"},
	{ID: "zf_094", Name: "zf_094 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_094"},
	{ID: "zf_099", Name: "zf_099 (Bilingual Female)", Gender: "female", Description: "Bilingual female speaker zf_099"},
	{ID: "zm_009", Name: "zm_009 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_009"},
	{ID: "zm_010", Name: "zm_010 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_010"},
	{ID: "zm_011", Name: "zm_011 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_011"},
	{ID: "zm_012", Name: "zm_012 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_012"},
	{ID: "zm_013", Name: "zm_013 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_013"},
	{ID: "zm_014", Name: "zm_014 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_014"},
	{ID: "zm_015", Name: "zm_015 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_015"},
	{ID: "zm_016", Name: "zm_016 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_016"},
	{ID: "zm_020", Name: "zm_020 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_020"},
	{ID: "zm_025", Name: "zm_025 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_025"},
	{ID: "zm_029", Name: "zm_029 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_029"},
	{ID: "zm_030", Name: "zm_030 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_030"},
	{ID: "zm_031", Name: "zm_031 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_031"},
	{ID: "zm_033", Name: "zm_033 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_033"},
	{ID: "zm_034", Name: "zm_034 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_034"},
	{ID: "zm_035", Name: "zm_035 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_035"},
	{ID: "zm_037", Name: "zm_037 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_037"},
	{ID: "zm_041", Name: "zm_041 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_041"},
	{ID: "zm_045", Name: "zm_045 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_045"},
	{ID: "zm_050", Name: "zm_050 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_050"},
	{ID: "zm_052", Name: "zm_052 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_052"},
	{ID: "zm_053", Name: "zm_053 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_053"},
	{ID: "zm_054", Name: "zm_054 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_054"},
	{ID: "zm_055", Name: "zm_055 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_055"},
	{ID: "zm_056", Name: "zm_056 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_056"},
	{ID: "zm_057", Name: "zm_057 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_057"},
	{ID: "zm_058", Name: "zm_058 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_058"},
	{ID: "zm_061", Name: "zm_061 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_061"},
	{ID: "zm_062", Name: "zm_062 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_062"},
	{ID: "zm_063", Name: "zm_063 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_063"},
	{ID: "zm_064", Name: "zm_064 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_064"},
	{ID: "zm_065", Name: "zm_065 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_065"},
	{ID: "zm_066", Name: "zm_066 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_066"},
	{ID: "zm_068", Name: "zm_068 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_068"},
	{ID: "zm_069", Name: "zm_069 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_069"},
	{ID: "zm_080", Name: "zm_080 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_080"},
	{ID: "zm_081", Name: "zm_081 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_081"},
	{ID: "zm_082", Name: "zm_082 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_082"},
	{ID: "zm_089", Name: "zm_089 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_089"},
	{ID: "zm_091", Name: "zm_091 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_091"},
	{ID: "zm_095", Name: "zm_095 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_095"},
	{ID: "zm_096", Name: "zm_096 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_096"},
	{ID: "zm_097", Name: "zm_097 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_097"},
	{ID: "zm_098", Name: "zm_098 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_098"},
	{ID: "zm_100", Name: "zm_100 (Bilingual Male)", Gender: "male", Description: "Bilingual male speaker zm_100"},
}

// AvailableKokoroV10Voices contains the 54 official speaker profiles for kokoro-multi-lang-v1_0.
var AvailableKokoroV10Voices = []VoiceProfile{
	// American English Female (af_)
	{ID: "af_alloy", Name: "Alloy (American Female)", Gender: "female", Description: "Clear, adaptable American English female", Language: "en-us"},
	{ID: "af_aoede", Name: "Aoede (American Female)", Gender: "female", Description: "Expressive American English female", Language: "en-us"},
	{ID: "af_bella", Name: "Bella (American Female)", Gender: "female", Description: "Friendly and bright American English female", Language: "en-us"},
	{ID: "af_heart", Name: "Heart (American Female, Default)", Gender: "female", Description: "Warm, natural flagship American English female", Language: "en-us"},
	{ID: "af_jessica", Name: "Jessica (American Female)", Gender: "female", Description: "Conversational American English female", Language: "en-us"},
	{ID: "af_kore", Name: "Kore (American Female)", Gender: "female", Description: "Calm, narrative American English female", Language: "en-us"},
	{ID: "af_nicole", Name: "Nicole (American Female)", Gender: "female", Description: "Professional, articulate American English female", Language: "en-us"},
	{ID: "af_nova", Name: "Nova (American Female)", Gender: "female", Description: "Warm, resonant American English female", Language: "en-us"},
	{ID: "af_river", Name: "River (American Female)", Gender: "female", Description: "Relaxed American English female", Language: "en-us"},
	{ID: "af_sarah", Name: "Sarah (American Female)", Gender: "female", Description: "Casual, energetic American English female", Language: "en-us"},
	{ID: "af_sky", Name: "Sky (American Female)", Gender: "female", Description: "Soft, melodic conversational American voice", Language: "en-us"},

	// American English Male (am_)
	{ID: "am_adam", Name: "Adam (American Male)", Gender: "male", Description: "Deep, crisp American English male", Language: "en-us"},
	{ID: "am_echo", Name: "Echo (American Male)", Gender: "male", Description: "Clear, neutral American English male", Language: "en-us"},
	{ID: "am_eric", Name: "Eric (American Male)", Gender: "male", Description: "Warm, friendly American English male", Language: "en-us"},
	{ID: "am_fenrir", Name: "Fenrir (American Male)", Gender: "male", Description: "Strong, commanding American English male", Language: "en-us"},
	{ID: "am_liam", Name: "Liam (American Male)", Gender: "male", Description: "Conversational American English male", Language: "en-us"},
	{ID: "am_michael", Name: "Michael (American Male)", Gender: "male", Description: "Neutral and professional American male", Language: "en-us"},
	{ID: "am_onyx", Name: "Onyx (American Male)", Gender: "male", Description: "Deep, resonant American English male", Language: "en-us"},
	{ID: "am_puck", Name: "Puck (American Male)", Gender: "male", Description: "Playful, light American English male", Language: "en-us"},
	{ID: "am_santa", Name: "Santa (American Male)", Gender: "male", Description: "Jovial American English male", Language: "en-us"},

	// British English Female (bf_)
	{ID: "bf_alice", Name: "Alice (British Female)", Gender: "female", Description: "Clear, crisp British English female", Language: "en-gb"},
	{ID: "bf_emma", Name: "Emma (British Female)", Gender: "female", Description: "Polite, articulate British English female", Language: "en-gb"},
	{ID: "bf_isabella", Name: "Isabella (British Female)", Gender: "female", Description: "Warm British conversational female", Language: "en-gb"},
	{ID: "bf_lily", Name: "Lily (British Female)", Gender: "female", Description: "Soft, expressive British English female", Language: "en-gb"},

	// British English Male (bm_)
	{ID: "bm_daniel", Name: "Daniel (British Male)", Gender: "male", Description: "Classic, formal British English male", Language: "en-gb"},
	{ID: "bm_fable", Name: "Fable (British Male)", Gender: "male", Description: "Narrative, dramatic British English male", Language: "en-gb"},
	{ID: "bm_george", Name: "George (British Male)", Gender: "male", Description: "Refined, classic British English male", Language: "en-gb"},
	{ID: "bm_lewis", Name: "Lewis (British Male)", Gender: "male", Description: "Deep, resonant British narrator male", Language: "en-gb"},

	// Spanish (ef_ / em_)
	{ID: "ef_dora", Name: "Dora (Spanish Female)", Gender: "female", Description: "Natural, expressive Spanish female", Language: "es"},
	{ID: "em_alex", Name: "Alex (Spanish Male)", Gender: "male", Description: "Conversational Spanish male", Language: "es"},
	{ID: "em_santa", Name: "Santa (Spanish Male)", Gender: "male", Description: "Warm, festive Spanish male", Language: "es"},

	// French (ff_)
	{ID: "ff_siwis", Name: "Siwis (French Female)", Gender: "female", Description: "Natural, melodic French female", Language: "fr"},

	// Hindi (hf_ / hm_)
	{ID: "hf_alpha", Name: "Alpha (Hindi Female)", Gender: "female", Description: "Clear Hindi female speaker Alpha", Language: "hi"},
	{ID: "hf_beta", Name: "Beta (Hindi Female)", Gender: "female", Description: "Natural Hindi female speaker Beta", Language: "hi"},
	{ID: "hm_omega", Name: "Omega (Hindi Male)", Gender: "male", Description: "Resonant Hindi male speaker Omega", Language: "hi"},
	{ID: "hm_psi", Name: "Psi (Hindi Male)", Gender: "male", Description: "Conversational Hindi male speaker Psi", Language: "hi"},

	// Italian (if_ / im_)
	{ID: "if_sara", Name: "Sara (Italian Female)", Gender: "female", Description: "Warm, expressive Italian female", Language: "it"},
	{ID: "im_nicola", Name: "Nicola (Italian Male)", Gender: "male", Description: "Clear, natural Italian male", Language: "it"},

	// Japanese (jf_ / jm_)
	{ID: "jf_alpha", Name: "Alpha (Japanese Female)", Gender: "female", Description: "Clear Japanese female speaker Alpha", Language: "ja"},
	{ID: "jf_gongitsune", Name: "Gongitsune (Japanese Female)", Gender: "female", Description: "Storytelling Japanese female narrator", Language: "ja"},
	{ID: "jf_nezumi", Name: "Nezumi (Japanese Female)", Gender: "female", Description: "Lively Japanese female speaker", Language: "ja"},
	{ID: "jf_tebukuro", Name: "Tebukuro (Japanese Female)", Gender: "female", Description: "Gentle Japanese female speaker", Language: "ja"},
	{ID: "jm_kumo", Name: "Kumo (Japanese Male)", Gender: "male", Description: "Natural Japanese male narrator", Language: "ja"},

	// Brazilian Portuguese (pf_ / pm_)
	{ID: "pf_dora", Name: "Dora (Brazilian Portuguese Female)", Gender: "female", Description: "Warm Brazilian Portuguese female", Language: "pt-br"},
	{ID: "pm_alex", Name: "Alex (Brazilian Portuguese Male)", Gender: "male", Description: "Natural Brazilian Portuguese male", Language: "pt-br"},
	{ID: "pm_santa", Name: "Santa (Brazilian Portuguese Male)", Gender: "male", Description: "Festive Brazilian Portuguese male", Language: "pt-br"},

	// Mandarin Chinese (zf_ / zm_)
	{ID: "zf_xiaobei", Name: "Xiaobei (Mandarin Female)", Gender: "female", Description: "Warm, articulate Mandarin female", Language: "zh"},
	{ID: "zf_xiaoni", Name: "Xiaoni (Mandarin Female)", Gender: "female", Description: "Lively Mandarin female speaker", Language: "zh"},
	{ID: "zf_xiaoxiao", Name: "Xiaoxiao (Mandarin Female)", Gender: "female", Description: "Conversational Mandarin female", Language: "zh"},
	{ID: "zf_xiaoyi", Name: "Xiaoyi (Mandarin Female)", Gender: "female", Description: "Gentle Mandarin female speaker", Language: "zh"},
	{ID: "zm_yunjian", Name: "Yunjian (Mandarin Male)", Gender: "male", Description: "Deep, resonant Mandarin male narrator", Language: "zh"},
	{ID: "zm_yunxi", Name: "Yunxi (Mandarin Male)", Gender: "male", Description: "Clear, youthful Mandarin male", Language: "zh"},
	{ID: "zm_yunxia", Name: "Yunxia (Mandarin Male)", Gender: "male", Description: "Natural, friendly Mandarin male", Language: "zh"},
	{ID: "zm_yunyang", Name: "Yunyang (Mandarin Male)", Gender: "male", Description: "Authoritative Mandarin male broadcast voice", Language: "zh"},
}

// AvailableKokoroV019Voices contains the 11 legacy English speaker profiles for kokoro-en-v0_19.
var AvailableKokoroV019Voices = []VoiceProfile{
	{ID: "af", Name: "Heart (American Female, Default)", Gender: "female", Description: "Warm, natural American English"},
	{ID: "am_adam", Name: "Adam (American Male)", Gender: "male", Description: "Deep, crisp American English male"},
	{ID: "am_michael", Name: "Michael (American Male)", Gender: "male", Description: "Neutral and professional American male"},
	{ID: "bm_george", Name: "George (British Male)", Gender: "male", Description: "Refined, classic British English male"},
	{ID: "bm_lewis", Name: "Lewis (British Male)", Gender: "male", Description: "Deep, resonant British narrator male"},
	{ID: "af_bella", Name: "Bella (American Female)", Gender: "female", Description: "Friendly and expressive American female"},
	{ID: "af_nicole", Name: "Nicole (American Female)", Gender: "female", Description: "Calm, clear American narrator female"},
	{ID: "af_sarah", Name: "Sarah (American Female)", Gender: "female", Description: "Casual and bright American female"},
	{ID: "af_sky", Name: "Sky (American Female)", Gender: "female", Description: "Soft, melodic conversational American voice"},
	{ID: "bf_emma", Name: "Emma (British Female)", Gender: "female", Description: "Polite, articulate British English female"},
	{ID: "bf_isabella", Name: "Isabella (British Female)", Gender: "female", Description: "Warm British conversational female"},
}

// KokoroV11VoiceToSID maps kokoro-multi-lang-v1_1 voice names to their respective speaker IDs (0-102).
var KokoroV11VoiceToSID = map[string]int{
	"af_maple": 0,
	"af_sol": 1,
	"bf_vale": 2,
	"zf_001": 3,
	"zf_002": 4,
	"zf_003": 5,
	"zf_004": 6,
	"zf_005": 7,
	"zf_006": 8,
	"zf_007": 9,
	"zf_008": 10,
	"zf_017": 11,
	"zf_018": 12,
	"zf_019": 13,
	"zf_021": 14,
	"zf_022": 15,
	"zf_023": 16,
	"zf_024": 17,
	"zf_026": 18,
	"zf_027": 19,
	"zf_028": 20,
	"zf_032": 21,
	"zf_036": 22,
	"zf_038": 23,
	"zf_039": 24,
	"zf_040": 25,
	"zf_042": 26,
	"zf_043": 27,
	"zf_044": 28,
	"zf_046": 29,
	"zf_047": 30,
	"zf_048": 31,
	"zf_049": 32,
	"zf_051": 33,
	"zf_059": 34,
	"zf_060": 35,
	"zf_067": 36,
	"zf_070": 37,
	"zf_071": 38,
	"zf_072": 39,
	"zf_073": 40,
	"zf_074": 41,
	"zf_075": 42,
	"zf_076": 43,
	"zf_077": 44,
	"zf_078": 45,
	"zf_079": 46,
	"zf_083": 47,
	"zf_084": 48,
	"zf_085": 49,
	"zf_086": 50,
	"zf_087": 51,
	"zf_088": 52,
	"zf_090": 53,
	"zf_092": 54,
	"zf_093": 55,
	"zf_094": 56,
	"zf_099": 57,
	"zm_009": 58,
	"zm_010": 59,
	"zm_011": 60,
	"zm_012": 61,
	"zm_013": 62,
	"zm_014": 63,
	"zm_015": 64,
	"zm_016": 65,
	"zm_020": 66,
	"zm_025": 67,
	"zm_029": 68,
	"zm_030": 69,
	"zm_031": 70,
	"zm_033": 71,
	"zm_034": 72,
	"zm_035": 73,
	"zm_037": 74,
	"zm_041": 75,
	"zm_045": 76,
	"zm_050": 77,
	"zm_052": 78,
	"zm_053": 79,
	"zm_054": 80,
	"zm_055": 81,
	"zm_056": 82,
	"zm_057": 83,
	"zm_058": 84,
	"zm_061": 85,
	"zm_062": 86,
	"zm_063": 87,
	"zm_064": 88,
	"zm_065": 89,
	"zm_066": 90,
	"zm_068": 91,
	"zm_069": 92,
	"zm_080": 93,
	"zm_081": 94,
	"zm_082": 95,
	"zm_089": 96,
	"zm_091": 97,
	"zm_095": 98,
	"zm_096": 99,
	"zm_097": 100,
	"zm_098": 101,
	"zm_100": 102,
	"af": 0,
	"heart": 0,
	"maple": 0,
	"sol": 1,
	"vale": 2,
}

// KokoroV10VoiceToSID maps kokoro-multi-lang-v1_0 voice names to their respective speaker IDs (0-53).
var KokoroV10VoiceToSID = map[string]int{
	"af_alloy":      0,
	"af_aoede":      1,
	"af_bella":      2,
	"af_heart":      3,
	"af_jessica":    4,
	"af_kore":       5,
	"af_nicole":     6,
	"af_nova":       7,
	"af_river":      8,
	"af_sarah":      9,
	"af_sky":        10,
	"am_adam":       11,
	"am_echo":       12,
	"am_eric":       13,
	"am_fenrir":     14,
	"am_liam":       15,
	"am_michael":    16,
	"am_onyx":       17,
	"am_puck":       18,
	"am_santa":      19,
	"bf_alice":      20,
	"bf_emma":       21,
	"bf_isabella":   22,
	"bf_lily":       23,
	"bm_daniel":     24,
	"bm_fable":      25,
	"bm_george":     26,
	"bm_lewis":      27,
	"ef_dora":       28,
	"em_alex":       29,
	"ff_siwis":      30,
	"hf_alpha":      31,
	"hf_beta":       32,
	"hm_omega":      33,
	"hm_psi":        34,
	"if_sara":       35,
	"im_nicola":      36,
	"jf_alpha":      37,
	"jf_gongitsune": 38,
	"jf_nezumi":     39,
	"jf_tebukuro":   40,
	"jm_kumo":       41,
	"pf_dora":       42,
	"pm_alex":       43,
	"pm_santa":      44,
	"zf_xiaobei":    45,
	"zf_xiaoni":     46,
	"zf_xiaoxiao":   47,
	"zf_xiaoyi":     48,
	"zm_yunjian":    49,
	"zm_yunxi":      50,
	"zm_yunxia":     51,
	"zm_yunyang":    52,
	"em_santa":      53,

	// Short aliases & fallbacks
	"af":        3,
	"heart":     3,
	"alloy":     0,
	"aoede":     1,
	"bella":     2,
	"jessica":   4,
	"kore":      5,
	"nicole":    6,
	"nova":      7,
	"river":     8,
	"sarah":     9,
	"sky":       10,
	"adam":      11,
	"echo":      12,
	"eric":      13,
	"fenrir":    14,
	"liam":      15,
	"michael":   16,
	"onyx":      17,
	"puck":      18,
	"alice":     20,
	"emma":      21,
	"isabella":  22,
	"lily":      23,
	"daniel":    24,
	"fable":     25,
	"george":    26,
	"lewis":     27,
	"dora":      28,
	"alex":      29,
	"siwis":     30,
	"sara":      35,
	"nicola":    36,
	"kumo":      41,
	"xiaobei":   45,
	"xiaoni":    46,
	"xiaoxiao":  47,
	"xiaoyi":    48,
	"yunjian":   49,
	"yunxi":     50,
	"yunxia":    51,
	"yunyang":   52,
	"santa":     53,
}

// KokoroV019VoiceToSID maps kokoro-en-v0_19 voice names to their respective speaker IDs (0-10).
var KokoroV019VoiceToSID = map[string]int{
	"af": 0,
	"af_heart": 0,
	"heart": 0,
	"af_bella": 1,
	"bella": 1,
	"af_nicole": 2,
	"nicole": 2,
	"af_alloy": 2,
	"alloy": 2,
	"af_sarah": 3,
	"sarah": 3,
	"af_sky": 4,
	"sky": 4,
	"af_aoede": 4,
	"aoede": 4,
	"am_adam": 5,
	"adam": 5,
	"am_michael": 6,
	"michael": 6,
	"bf_emma": 7,
	"emma": 7,
	"bf_isabella": 8,
	"isabella": 8,
	"bm_george": 9,
	"george": 9,
	"am_fenrir": 9,
	"fenrir": 9,
	"bm_lewis": 10,
	"lewis": 10,
	"am_puck": 10,
	"puck": 10,
}
